DROP TABLE IF EXISTS `Enrollments`;

CREATE TABLE `Enrollments` (
	id INT AUTO_INCREMENT PRIMARY KEY,
	subject VARCHAR(30) NOT NULL,
	teacherId INT NOT NULL,
	studentId INT NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);