DROP TABLE IF EXISTS `Students`;

CREATE TABLE `Students` (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(30) NOT NULL,
	password VARCHAR(128) NOT NULL,
	name VARCHAR(50) NOT NULL,
	age TINYINT NOT NULL,
	mobile CHAR(10) NOT NULL,
	created DATETIME DEFAULT CURRENT_TIMESTAMP
);