/*
 * This file is generated by jOOQ.
 */
package com.classDojo.entities.meta;


import com.classDojo.entities.meta.tables.Enrollments;
import com.classDojo.entities.meta.tables.Studentattendances;
import com.classDojo.entities.meta.tables.Students;
import com.classDojo.entities.meta.tables.Subjects;
import com.classDojo.entities.meta.tables.Teachers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classdojo extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ClassDojo</code>
     */
    public static final Classdojo CLASSDOJO = new Classdojo();

    /**
     * The table <code>ClassDojo.Enrollments</code>.
     */
    public final Enrollments ENROLLMENTS = Enrollments.ENROLLMENTS;

    /**
     * The table <code>ClassDojo.StudentAttendances</code>.
     */
    public final Studentattendances STUDENTATTENDANCES = Studentattendances.STUDENTATTENDANCES;

    /**
     * The table <code>ClassDojo.Students</code>.
     */
    public final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>ClassDojo.Subjects</code>.
     */
    public final Subjects SUBJECTS = Subjects.SUBJECTS;

    /**
     * The table <code>ClassDojo.Teachers</code>.
     */
    public final Teachers TEACHERS = Teachers.TEACHERS;

    /**
     * No further instances allowed
     */
    private Classdojo() {
        super("ClassDojo", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Enrollments.ENROLLMENTS,
            Studentattendances.STUDENTATTENDANCES,
            Students.STUDENTS,
            Subjects.SUBJECTS,
            Teachers.TEACHERS);
    }
}
