/*
 * This file is generated by jOOQ.
 */
package com.classDojo.entities.meta;


import com.classDojo.entities.meta.tables.Enrollments;
import com.classDojo.entities.meta.tables.Studentattendances;
import com.classDojo.entities.meta.tables.Students;
import com.classDojo.entities.meta.tables.Subjects;
import com.classDojo.entities.meta.tables.Teachers;
import com.classDojo.entities.meta.tables.records.EnrollmentsRecord;
import com.classDojo.entities.meta.tables.records.StudentattendancesRecord;
import com.classDojo.entities.meta.tables.records.StudentsRecord;
import com.classDojo.entities.meta.tables.records.SubjectsRecord;
import com.classDojo.entities.meta.tables.records.TeachersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * ClassDojo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EnrollmentsRecord> KEY_ENROLLMENTS_PRIMARY = Internal.createUniqueKey(Enrollments.ENROLLMENTS, DSL.name("KEY_Enrollments_PRIMARY"), new TableField[] { Enrollments.ENROLLMENTS.ID }, true);
    public static final UniqueKey<StudentattendancesRecord> KEY_STUDENTATTENDANCES_PRIMARY = Internal.createUniqueKey(Studentattendances.STUDENTATTENDANCES, DSL.name("KEY_StudentAttendances_PRIMARY"), new TableField[] { Studentattendances.STUDENTATTENDANCES.ID }, true);
    public static final UniqueKey<StudentsRecord> KEY_STUDENTS_PRIMARY = Internal.createUniqueKey(Students.STUDENTS, DSL.name("KEY_Students_PRIMARY"), new TableField[] { Students.STUDENTS.ID }, true);
    public static final UniqueKey<SubjectsRecord> KEY_SUBJECTS_PRIMARY = Internal.createUniqueKey(Subjects.SUBJECTS, DSL.name("KEY_Subjects_PRIMARY"), new TableField[] { Subjects.SUBJECTS.ID }, true);
    public static final UniqueKey<TeachersRecord> KEY_TEACHERS_PRIMARY = Internal.createUniqueKey(Teachers.TEACHERS, DSL.name("KEY_Teachers_PRIMARY"), new TableField[] { Teachers.TEACHERS.ID }, true);
}
