/*
 * This file is generated by jOOQ.
 */
package com.classDojo.entities.meta;


import com.classDojo.entities.meta.tables.Enrollments;
import com.classDojo.entities.meta.tables.Studentattendances;
import com.classDojo.entities.meta.tables.Students;
import com.classDojo.entities.meta.tables.Subjects;
import com.classDojo.entities.meta.tables.Teachers;


/**
 * Convenience access to all tables in ClassDojo.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ClassDojo.Enrollments</code>.
     */
    public static final Enrollments ENROLLMENTS = Enrollments.ENROLLMENTS;

    /**
     * The table <code>ClassDojo.StudentAttendances</code>.
     */
    public static final Studentattendances STUDENTATTENDANCES = Studentattendances.STUDENTATTENDANCES;

    /**
     * The table <code>ClassDojo.Students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>ClassDojo.Subjects</code>.
     */
    public static final Subjects SUBJECTS = Subjects.SUBJECTS;

    /**
     * The table <code>ClassDojo.Teachers</code>.
     */
    public static final Teachers TEACHERS = Teachers.TEACHERS;
}
