/*
 * This file is generated by jOOQ.
 */
package com.classDojo.entities.meta.tables.records;


import com.classDojo.entities.meta.tables.Enrollments;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnrollmentsRecord extends UpdatableRecordImpl<EnrollmentsRecord> implements Record5<Integer, String, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ClassDojo.Enrollments.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ClassDojo.Enrollments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ClassDojo.Enrollments.subject</code>.
     */
    public void setSubject(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ClassDojo.Enrollments.subject</code>.
     */
    public String getSubject() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ClassDojo.Enrollments.teacherId</code>.
     */
    public void setTeacherid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>ClassDojo.Enrollments.teacherId</code>.
     */
    public Integer getTeacherid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ClassDojo.Enrollments.studentId</code>.
     */
    public void setStudentid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ClassDojo.Enrollments.studentId</code>.
     */
    public Integer getStudentid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ClassDojo.Enrollments.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>ClassDojo.Enrollments.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Enrollments.ENROLLMENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Enrollments.ENROLLMENTS.SUBJECT;
    }

    @Override
    public Field<Integer> field3() {
        return Enrollments.ENROLLMENTS.TEACHERID;
    }

    @Override
    public Field<Integer> field4() {
        return Enrollments.ENROLLMENTS.STUDENTID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Enrollments.ENROLLMENTS.CREATED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSubject();
    }

    @Override
    public Integer component3() {
        return getTeacherid();
    }

    @Override
    public Integer component4() {
        return getStudentid();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSubject();
    }

    @Override
    public Integer value3() {
        return getTeacherid();
    }

    @Override
    public Integer value4() {
        return getStudentid();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public EnrollmentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EnrollmentsRecord value2(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public EnrollmentsRecord value3(Integer value) {
        setTeacherid(value);
        return this;
    }

    @Override
    public EnrollmentsRecord value4(Integer value) {
        setStudentid(value);
        return this;
    }

    @Override
    public EnrollmentsRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public EnrollmentsRecord values(Integer value1, String value2, Integer value3, Integer value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnrollmentsRecord
     */
    public EnrollmentsRecord() {
        super(Enrollments.ENROLLMENTS);
    }

    /**
     * Create a detached, initialised EnrollmentsRecord
     */
    public EnrollmentsRecord(Integer id, String subject, Integer teacherid, Integer studentid, LocalDateTime created) {
        super(Enrollments.ENROLLMENTS);

        setId(id);
        setSubject(subject);
        setTeacherid(teacherid);
        setStudentid(studentid);
        setCreated(created);
    }
}
