/*
 * This file is generated by jOOQ.
 */
package com.classDojo.entities.meta.tables.records;


import com.classDojo.entities.meta.tables.Students;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentsRecord extends UpdatableRecordImpl<StudentsRecord> implements Record7<Integer, String, String, String, Byte, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ClassDojo.Students.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ClassDojo.Students.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ClassDojo.Students.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ClassDojo.Students.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ClassDojo.Students.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ClassDojo.Students.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ClassDojo.Students.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ClassDojo.Students.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ClassDojo.Students.age</code>.
     */
    public void setAge(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>ClassDojo.Students.age</code>.
     */
    public Byte getAge() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>ClassDojo.Students.mobile</code>.
     */
    public void setMobile(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ClassDojo.Students.mobile</code>.
     */
    public String getMobile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ClassDojo.Students.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>ClassDojo.Students.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, Byte, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, Byte, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Students.STUDENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Students.STUDENTS.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return Students.STUDENTS.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return Students.STUDENTS.NAME;
    }

    @Override
    public Field<Byte> field5() {
        return Students.STUDENTS.AGE;
    }

    @Override
    public Field<String> field6() {
        return Students.STUDENTS.MOBILE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Students.STUDENTS.CREATED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Byte component5() {
        return getAge();
    }

    @Override
    public String component6() {
        return getMobile();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Byte value5() {
        return getAge();
    }

    @Override
    public String value6() {
        return getMobile();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public StudentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StudentsRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public StudentsRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public StudentsRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public StudentsRecord value5(Byte value) {
        setAge(value);
        return this;
    }

    @Override
    public StudentsRecord value6(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public StudentsRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public StudentsRecord values(Integer value1, String value2, String value3, String value4, Byte value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentsRecord
     */
    public StudentsRecord() {
        super(Students.STUDENTS);
    }

    /**
     * Create a detached, initialised StudentsRecord
     */
    public StudentsRecord(Integer id, String email, String password, String name, Byte age, String mobile, LocalDateTime created) {
        super(Students.STUDENTS);

        setId(id);
        setEmail(email);
        setPassword(password);
        setName(name);
        setAge(age);
        setMobile(mobile);
        setCreated(created);
    }
}
