/*
 * This file is generated by jOOQ.
 */
package com.classDojo.entities.meta.tables.records;


import com.classDojo.entities.meta.tables.Subjects;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectsRecord extends UpdatableRecordImpl<SubjectsRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ClassDojo.Subjects.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ClassDojo.Subjects.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ClassDojo.Subjects.teacherId</code>.
     */
    public void setTeacherid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ClassDojo.Subjects.teacherId</code>.
     */
    public Integer getTeacherid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ClassDojo.Subjects.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ClassDojo.Subjects.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Subjects.SUBJECTS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Subjects.SUBJECTS.TEACHERID;
    }

    @Override
    public Field<String> field3() {
        return Subjects.SUBJECTS.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTeacherid();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTeacherid();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public SubjectsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SubjectsRecord value2(Integer value) {
        setTeacherid(value);
        return this;
    }

    @Override
    public SubjectsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public SubjectsRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectsRecord
     */
    public SubjectsRecord() {
        super(Subjects.SUBJECTS);
    }

    /**
     * Create a detached, initialised SubjectsRecord
     */
    public SubjectsRecord(Integer id, Integer teacherid, String name) {
        super(Subjects.SUBJECTS);

        setId(id);
        setTeacherid(teacherid);
        setName(name);
    }
}
