/*
 * This file is generated by jOOQ.
 */
package com.classDojo.entities.meta.tables.records;


import com.classDojo.entities.meta.tables.Teachers;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachersRecord extends UpdatableRecordImpl<TeachersRecord> implements Record7<Integer, String, String, String, Byte, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ClassDojo.Teachers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ClassDojo.Teachers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ClassDojo.Teachers.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ClassDojo.Teachers.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ClassDojo.Teachers.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ClassDojo.Teachers.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ClassDojo.Teachers.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ClassDojo.Teachers.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ClassDojo.Teachers.age</code>.
     */
    public void setAge(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>ClassDojo.Teachers.age</code>.
     */
    public Byte getAge() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>ClassDojo.Teachers.mobile</code>.
     */
    public void setMobile(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ClassDojo.Teachers.mobile</code>.
     */
    public String getMobile() {
        return (String) get(5);
    }

    /**
     * Setter for <code>ClassDojo.Teachers.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>ClassDojo.Teachers.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, Byte, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, Byte, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Teachers.TEACHERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Teachers.TEACHERS.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return Teachers.TEACHERS.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return Teachers.TEACHERS.NAME;
    }

    @Override
    public Field<Byte> field5() {
        return Teachers.TEACHERS.AGE;
    }

    @Override
    public Field<String> field6() {
        return Teachers.TEACHERS.MOBILE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Teachers.TEACHERS.CREATED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public Byte component5() {
        return getAge();
    }

    @Override
    public String component6() {
        return getMobile();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public Byte value5() {
        return getAge();
    }

    @Override
    public String value6() {
        return getMobile();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public TeachersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TeachersRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public TeachersRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public TeachersRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public TeachersRecord value5(Byte value) {
        setAge(value);
        return this;
    }

    @Override
    public TeachersRecord value6(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public TeachersRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public TeachersRecord values(Integer value1, String value2, String value3, String value4, Byte value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeachersRecord
     */
    public TeachersRecord() {
        super(Teachers.TEACHERS);
    }

    /**
     * Create a detached, initialised TeachersRecord
     */
    public TeachersRecord(Integer id, String email, String password, String name, Byte age, String mobile, LocalDateTime created) {
        super(Teachers.TEACHERS);

        setId(id);
        setEmail(email);
        setPassword(password);
        setName(name);
        setAge(age);
        setMobile(mobile);
        setCreated(created);
    }
}
