/*
 * This file is generated by jOOQ.
 */
package com.classDojo.entities.meta.tables;


import com.classDojo.entities.meta.Classdojo;
import com.classDojo.entities.meta.Keys;
import com.classDojo.entities.meta.tables.records.SubjectsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subjects extends TableImpl<SubjectsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ClassDojo.Subjects</code>
     */
    public static final Subjects SUBJECTS = new Subjects();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubjectsRecord> getRecordType() {
        return SubjectsRecord.class;
    }

    /**
     * The column <code>ClassDojo.Subjects.id</code>.
     */
    public final TableField<SubjectsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ClassDojo.Subjects.teacherId</code>.
     */
    public final TableField<SubjectsRecord, Integer> TEACHERID = createField(DSL.name("teacherId"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ClassDojo.Subjects.name</code>.
     */
    public final TableField<SubjectsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    private Subjects(Name alias, Table<SubjectsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Subjects(Name alias, Table<SubjectsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ClassDojo.Subjects</code> table reference
     */
    public Subjects(String alias) {
        this(DSL.name(alias), SUBJECTS);
    }

    /**
     * Create an aliased <code>ClassDojo.Subjects</code> table reference
     */
    public Subjects(Name alias) {
        this(alias, SUBJECTS);
    }

    /**
     * Create a <code>ClassDojo.Subjects</code> table reference
     */
    public Subjects() {
        this(DSL.name("Subjects"), null);
    }

    public <O extends Record> Subjects(Table<O> child, ForeignKey<O, SubjectsRecord> key) {
        super(child, key, SUBJECTS);
    }

    @Override
    public Schema getSchema() {
        return Classdojo.CLASSDOJO;
    }

    @Override
    public Identity<SubjectsRecord, Integer> getIdentity() {
        return (Identity<SubjectsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SubjectsRecord> getPrimaryKey() {
        return Keys.KEY_SUBJECTS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SubjectsRecord>> getKeys() {
        return Arrays.<UniqueKey<SubjectsRecord>>asList(Keys.KEY_SUBJECTS_PRIMARY);
    }

    @Override
    public Subjects as(String alias) {
        return new Subjects(DSL.name(alias), this);
    }

    @Override
    public Subjects as(Name alias) {
        return new Subjects(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Subjects rename(String name) {
        return new Subjects(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Subjects rename(Name name) {
        return new Subjects(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
