/*
 * This file is generated by jOOQ.
 */
package com.classDojo.entities.meta.tables;


import com.classDojo.entities.meta.Classdojo;
import com.classDojo.entities.meta.Keys;
import com.classDojo.entities.meta.tables.records.TeachersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teachers extends TableImpl<TeachersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ClassDojo.Teachers</code>
     */
    public static final Teachers TEACHERS = new Teachers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeachersRecord> getRecordType() {
        return TeachersRecord.class;
    }

    /**
     * The column <code>ClassDojo.Teachers.id</code>.
     */
    public final TableField<TeachersRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>ClassDojo.Teachers.email</code>.
     */
    public final TableField<TeachersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>ClassDojo.Teachers.password</code>.
     */
    public final TableField<TeachersRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>ClassDojo.Teachers.name</code>.
     */
    public final TableField<TeachersRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>ClassDojo.Teachers.age</code>.
     */
    public final TableField<TeachersRecord, Byte> AGE = createField(DSL.name("age"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>ClassDojo.Teachers.mobile</code>.
     */
    public final TableField<TeachersRecord, String> MOBILE = createField(DSL.name("mobile"), SQLDataType.CHAR(10).nullable(false), this, "");

    /**
     * The column <code>ClassDojo.Teachers.created</code>.
     */
    public final TableField<TeachersRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Teachers(Name alias, Table<TeachersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Teachers(Name alias, Table<TeachersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ClassDojo.Teachers</code> table reference
     */
    public Teachers(String alias) {
        this(DSL.name(alias), TEACHERS);
    }

    /**
     * Create an aliased <code>ClassDojo.Teachers</code> table reference
     */
    public Teachers(Name alias) {
        this(alias, TEACHERS);
    }

    /**
     * Create a <code>ClassDojo.Teachers</code> table reference
     */
    public Teachers() {
        this(DSL.name("Teachers"), null);
    }

    public <O extends Record> Teachers(Table<O> child, ForeignKey<O, TeachersRecord> key) {
        super(child, key, TEACHERS);
    }

    @Override
    public Schema getSchema() {
        return Classdojo.CLASSDOJO;
    }

    @Override
    public Identity<TeachersRecord, Integer> getIdentity() {
        return (Identity<TeachersRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TeachersRecord> getPrimaryKey() {
        return Keys.KEY_TEACHERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<TeachersRecord>> getKeys() {
        return Arrays.<UniqueKey<TeachersRecord>>asList(Keys.KEY_TEACHERS_PRIMARY);
    }

    @Override
    public Teachers as(String alias) {
        return new Teachers(DSL.name(alias), this);
    }

    @Override
    public Teachers as(Name alias) {
        return new Teachers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Teachers rename(String name) {
        return new Teachers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Teachers rename(Name name) {
        return new Teachers(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, Byte, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
